n_pad/apps/account/urls.py
from django.urls import path, include

from . import views

app_name = "account"

urlpatterns = [
    path('register/', views.register, name = "register"),
    path('login/', views.login, name = "login"),
    path('logout/', views.logout, name = "logout"),
]

n_pad/apps/gx_styles/urls.py
from django.urls import path, include

app_name = "gx_styles"

urlpatterns = [

]

n_pad/apps/home/urls.py
from django.urls import path, include

from . import views

app_name = "home"

urlpatterns = [
    path('', views.index, name = "index"),
    path('create_note/', views.create_note, name = "create_note"),
    path('edit_note/<int:note_id>', views.edit_note, name = "edit_note")
]

n_pad/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.index, name = "index_index"),
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
    path('gx_styles/', include('gx_styles.urls')),
    path('account/', include('account.urls')),
    path('home/', include('home.urls'))
]

n_pad/apps/account/models.py
from django.db import models

# Create your models here.

n_pad/apps/bootstrap/models.py
from django.db import models

# Create your models here.

n_pad/apps/gx_styles/models.py
from django.db import models

# Create your models here.

n_pad/apps/home/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.
class Note(models.Model):
    author             = models.ForeignKey(User, on_delete = models.CASCADE)
    note_title         = models.CharField(verbose_name = "Note Title", max_length = 64)
    note_content       = models.TextField()
    note_date          = models.DateTimeField()
    note_last_modified = models.DateTimeField()

    verbose_name = "Note"
    verbose_name_plural = "Notes"

    def __str__(self):
        return self.author.username + " | " + self.note_title

    def modified(self):
        self.note_last_modified = timezone.now()

n_pad/apps/account/views.py
from django.shortcuts import render, redirect
from django.http import Http404, HttpResponse
from django.contrib.auth.models import User, auth
from django.contrib import messages

from django.core.exceptions import ObjectDoesNotExist

def register(request):
    if (request.user.is_authenticated):
        return redirect('home:index')
    
    if (request.method == "POST"):
        __email      = request.POST["email"]
        __username   = request.POST["username"]
        __password_1 = request.POST["password"]
        __password_2 = request.POST["password2"]

        if len(__password_1) < 8:
            messages.info(request, "Password should contain at least 8 characters")
            return redirect('account:register')

        if __password_1 != __password_2:
            messages.info(request, "Passwords don't match")
            return redirect('account:register')

        if User.objects.filter(username = __username).exists():
            messages.info(request, "User with username \"" + __username + "\" already exists")
            return redirect('account:register')
        elif User.objects.filter(email = __email).exists():
            messages.info(request, "Email \"" + __email + "\" is already being used")
            return redirect('account:register')

        user = User.objects.create_user(email = __email, username = __username, password = __password_1)
        user.save()

        messages.info(request, "You were successfully registered")
        return redirect('account:login')
    else:
        return render(request, 'account/register.html')

def login(request):
    if (request.user.is_authenticated):
        return redirect('home:index')
    
    if (request.method == "POST"):

        __username = request.POST["username"]
        __password = request.POST["password"]

        user = auth.authenticate(username = __username, password = __password)

        if user is None:
            messages.info(request, "Invalid username or password")
            return redirect('account:login')
        else:
            auth.login(request, user)
            return redirect('home:index')
    else:
        return render(request, 'account/login.html')

def logout(request):
    auth.logout(request)
    return redirect('home:index')

n_pad/apps/bootstrap/views.py
from django.shortcuts import render

# Create your views here.

n_pad/apps/gx_styles/views.py
from django.shortcuts import render

# Create your views here.

n_pad/apps/home/views.py
from django.shortcuts import render, redirect
from django.http import Http404

from django.utils import timezone

from .models import Note

def index(request):
    notes = None

    if (request.user.is_authenticated):
        notes = Note.objects.filter(author = request.user).order_by("-note_last_modified")

    return render(request, 'home.html', {
        "notes" : notes
    })

def create_note(request):
    t_now = timezone.now()
    note = Note(
        note_title = "",
        note_content = "",
        note_date = t_now,
        note_last_modified = t_now,
        author = request.user
    )
    note.save()

    return redirect('home:edit_note', note.id)

def edit_note(request, note_id):
    note = None

    try:
        # Assume notes do exist
        note = Note.objects.get(id = note_id)
    except Exception as e:
        print(e)
        return Http404(request)
    
    # POST
    if request.method == "POST":
        if request.POST["note_title"] == "" and request.POST["note_content"] == "":
            note.delete()
            return redirect('home:index')
        
        elif request.POST.get("cancel", False):
            pass
        else:
            note.note_title   = request.POST["note_title"]
            note.note_content = request.POST["note_content"]
            note.modified()
            note.save()

        return redirect('home:index')
    
    # GET
    return render(request, 'edit_note.html', {
        "note" : note
    })

n_pad/views.py
from django.shortcuts import redirect

def index(request):
    return redirect('home:index')

n_pad/templates/base.html
<!DOCTYPE html>
<html data-bs-theme="light">

<head>
    {% load static %}
    {% load bootstrap_icons %}
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">  
    <link href="{% static 'css/gx_styles.css' %}" rel="stylesheet" type="text/css">  
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <meta charset = "utf-8"/>
    <title>
        {% block page_title %}{% endblock %}
    </title>
</head>

<body class = "m-0 py-0">
    {% comment %} <div class = "gx-bg-img" style = "
        background-image: url({% static 'images/home_background.jpg' %});  
    "> {% endcomment %}
    <div>
        <div class = "py-4 bg-primary m-4 rounded">
            <a href="{% url 'home:index' %}" class = "px-5 text-light h1 text-decoration-none d-inline-block">N-Pad</a>

            <div class = "position-absolute end-0 d-inline-block px-5">
                
            {% if user.is_authenticated %}
                <h6 class = 'text-light d-inline-block px-3'>{{user.username}}</h6>
                <a href="{% url 'account:logout' %}" class = "btn btn-outline-light">Logout</a>
            {% else %}
                <a href="{% url 'account:login' %}" class = "btn btn-outline-light d-inline-block">Login</a>
                <a href="{% url 'account:register' %}" class = "btn btn-outline-light">Register</a>
            {% endif %}
            </div>
        </div>

        {% block page_content%}{% endblock %}
    </div>
</body>

</html>

n_pad/templates/edit_note.html
{% extends 'base.html' %}

{% load static %}

{% block page_title %}
    {% if note.note_title %}
    Edit: {{note.note_title}}
    {% else %}
    Edit: Untitled
    {% endif %}
{% endblock %}

{% block page_content %}
    <div class = "container">
        <div class = "row justify-content-center align-items-center">
            <div class = "col col-xl-8 col-lg-10 col-md-12">
                <form class = "form" action = "{% url 'home:edit_note' note.id %}" method = "post">
                    {% csrf_token %}
                    <div class = "input-group">
                        <span class = "input-group-text">Title:</span>
                        <input type = "text" class = "form-control" placeholder = "Untitled" name = "note_title" value = "{{note.note_title}}"></input>
                    </div>
                    <hr>
                    <p>Content:</p>
                    <textarea class = "form-control" placeholder = "Empty" rows = 25 name = "note_content">{{note.note_content}}</textarea>
                    <div class = "float-end my-3">
                        <input type = "submit" class = "btn btn-secondary" name = "cancel" value = "Cancel"></input>
                        <input type = "submit" class = "btn btn-primary" name = "save" value = "Save"></input>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

n_pad/templates/home.html
{% extends 'base.html' %}

{% load static %}
{% load bootstrap_icons %}
{% load note_card %}

{% block page_title %}
    Home
{% endblock %}

{% block page_content %}
    <div class = "container">
        <h1>Write Notes. Don't Forget Anything!</h1>
        <h4>{% lorem 20 w %}</h4>
    </div>
    <br>
    <hr>
    <br>

    {% if user.is_authenticated %}
    <div class = "container">
        <div class = "row my-3">
            <a href = "{% url 'home:create_note' %}" class = "card col-xl-3 col-lg-3 col-md-4 col-sm-5 col-5 m-3 p-0 btn btn-outline-primary">
                <div class = "m-auto">+ Create Note</div>
            </a>
            {% for note in notes %}
                {% draw_note_card note.note_title note.note_content note.note_last_modified note.id %}
            {% endfor %}
        </div>
    </div>
    {% else %}
    <div class = "container justify-content-center align-items-center col col-lg-6 col-md-8 col-sm-10">
        <div class = "card shadow-lg">
            <div class = "col p-4 d-inline">
                <h3>Let's start noting!</h3>
                <p>Please login or register to use our services</p>
                <a href = "{% url 'account:login' %}" class = "btn btn-primary d-block my-2">{%comment%}{% bs_icon 'box-arrow-in-right' %}{%endcomment%} Login</a>
                <a href = "{% url 'account:register' %}" class = "btn btn-primary d-block my-2">{%comment%}{% bs_icon 'plus-circle' %}{%endcomment%}Register</a>
            </div>
        </div>
    </div>
    {% endif %}
{% endblock %}

n_pad/templates/widgets/note_card.html
<div class = "card col-xl-3 col-lg-3 col-md-4 col-sm-5 col-5 m-3 p-0 d-flex">
    <div class = "card-header">
        <p class = "m-0 text-primary"><i>{{note_date}}</i></p>
        {% if note_title %}
            <h6 class = "text-nowrap text-truncate">{{note_title}}</h6>
        {% else %}
            <h6><i>Untitled</i></h6>
        {% endif %}
    </div>
    <div class = "card-body">
        <div class = "d-flex flex-column h-100">
            {% if note_content|length < 100 %}
                <p>{{note_content}}</p>
            {% else %}
                <p class = "gx-text-fading">{{note_content|slice:"0:100"}}...</p>
            {% endif %}
            <form action = "{% url 'home:edit_note' note_id %}" class = "mt-auto">
                {% csrf_token %}
                <button type = "submit" class = "btn btn-primary btn-block w-100">Edit</button>
            </form>
        </div>
    </div>
</div>